version: "3.9"
services:
  node:
    image: node
    container_name: node
    command: npm start
    depends_on: 
      - mongodb
    ports:
      - "3000:3000"
    volumes: 
      - .:/project
      - type: volume
        source: mynode
        target: /etc
    networks: 
      - app
    working_dir: /project
  mongodb:
    image: mongo
    container_name: mongodb
    volumes: 
      - mydb:/data
    ports:
      - "27017:27017"
    networks: 
      - app
volumes:
  mydb:
    external: true
  mynode:
    external: true
networks: 
  app:
    name: app