const SUCCESS = 200;
const CREATED = 201;
const NOT_FOUND = 404;
const INVALID_DATE = 422;
const INTERNAL_ERROR = 500;

module.exports = {
  SUCCESS,
  CREATED,
  NOT_FOUND,
  INVALID_DATE,
  INTERNAL_ERROR,
};
